with open("wiki/index.md", "a") as f:
    f.write("\n## Stub Pages (Created via Lint)\n")
    f.write("- [[tosafot]]\n")
    f.write("- [[talmud-yerushalmi]]\n")
    f.write("- [[haggai]]\n")
    f.write("- [[melchizedek]]\n")
    f.write("- [[sound-doctrine]]\n")
    f.write("- [[abraham]]\n")
    f.write("- [[godliness]]\n")
    f.write("- [[typology]]\n")
    f.write("- [[creation-ex-nihilo]]\n")
    f.write("- [[sacrifice]]\n")
    f.write("- [[evangelical-commentary]]\n")
    f.write("- [[f-f-bruce]]\n")
    f.write("- [[william-lane]]\n")
    f.write("- [[peter-obrien]]\n")
    f.write("- [[harold-attridge]]\n")
    f.write("- [[john-calvin]]\n")
    f.write("- [[rabbi-abraham-ben-david]]\n")
    f.write("- [[rabbenu-gershom]]\n")
    f.write("- [[sherira-gaon]]\n")
    f.write("- [[isaiah-job-servant-direction]]\n")
    f.write("- [[flood-universality]]\n")
    f.write("- [[jephthah-vow]]\n")
    f.write("- [[paris-trial-1240]]\n")
    f.write("- [[women-and-worship]]\n")
